CONSTRUCT {
    ?dhpUri dhpluso:diedIn ?dhpDeath .
    
    ?dhpDeath
        a dhpluso:Death ;
        dhpluso:wasDeathOf ?dhpUri ;
        dhpluso:hasTimeSpan ?dhpTimeSpan ;
        dcterms:created ?now ;
        dc:source ?authorityUri ;
    .

    ?dhpTimeSpan
        a dhpluso:Instant ;
        dhpluso:inXSDDate ?xsDate 
    .   
}
WHERE {
    {{ sparqlBlocks.initParameter }}
    {{ sparqlBlocks.endpoints }}    
    
    SERVICE ?af {
        ?authorityUri gndo:dateOfDeath ?date .
    }
    
    BIND(
        IF(
            BOUND(?date),
            IRI(CONCAT(STR(?dhpUri),'/death')),
            ?nothing
        )
        AS ?dhpDeath
    )
    
    BIND(
        IF(
            BOUND(?date),
            xsd:date(?date),
            ?nothing
        )
        AS ?xsDate
    )

    BIND(
        IF(
            BOUND(?xsDate),
            BNODE(),
            ?nothing
        )
        AS ?dhpTimeSpan
    )
}