CONSTRUCT {
    ?dhpUri rdfs:label ?label .
}
WHERE {
    {{ sparqlBlocks.initParameter }}
    {{ sparqlBlocks.endpoints }}
    
    SERVICE ?af {
        ?authorityUri bf:title/bf:mainTitle ?label .
    }
}