SELECT ?this
WHERE {
    {
        ?this a $class .
    }
    UNION
    {
        {{ sparqlBlocks.endpoints }}
        ?this a ?currentClass .
        SERVICE ?dhPLUSOntology {
            ?currentClass rdfs:subClassOf* $class .
        }
    }
}